GET http://localhost:3000/api/persons HTTP/1.1

###
GET http://localhost:3001/api/persons/hellothere HTTP/1.1

###
DELETE http://localhost:3001/api/persons/6014fa8655c5d826348f89fc HTTP/1.1

###
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Dan Holk",
    "number": "3343",
    "lastname": "not be added"
}